### PR TITLE
Add search to /admin/users

### PR DESCRIPTION
**Pull request by Greenheart**
A simple filtering-functionality for the view listing teachers implemented using jQuery for improved cross-browser compatability.

### CODE REVIEW

**Comment by hugolundin** [comment]
Are you able to search by email? Otherwise maybe that is a refinement to do before merging? 😊

**Comment by Greenheart** [comment]
Good idea! It's probably one line of change and I can do it tomorrow :)

torsdag 21 april 2016 skrev Hugo Lundin notifications@github.com:

**Comment by hugolundin** [comment]
Accidentally merged the pull reques. Great. Is there a way to revert it or should we live with it? @limpan

**Comment by Greenheart** [comment]
Lol. I guess you could (rebase or whatever it was) your local clone and
then force-push it to GitHub to override this and then I could re-open my
PR.

Or I could just submit another PR tomorrow with the additions like nothing
happened 😜

torsdag 21 april 2016 skrev Hugo Lundin notifications@github.com:

**Comment by Limpan** [comment]
https://help.github.com/articles/reverting-a-pull-request/

**Comment by Greenheart** [comment]
@hugolundin @Limpan Where should I point the PR my updated version of the search? ^^

/feature/admin-ui

or

/revert-1-feature/admin-ui

**Comment by hugolundin** [comment]
/feature/admin-ui

**Pull request merged**
